// <copyright file="PostDisassociates.cs" company="Microsoft">
// Copyright (c) 2012 All Rights Reserved
// </copyright>
// <author>Microsoft</author>
// <date>10/24/2012 3:35:36 PM</date>
// <summary>Implements the PostDisassociates Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace VerathonSolution.Plugins
{
    using System;
    using System.ServiceModel;
    using System.Linq;
    using System.Collections.Generic;

    using Microsoft.Xrm.Sdk;

    using Verathon.Crm.Entities;

    /// <summary>
    /// PostDisassociates Plugin.
    /// </summary>    
    public class PostDisassociates: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostDisassociates"/> class.
        /// </summary>
        public PostDisassociates()
            : base(typeof(PostDisassociates))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Disassociate", "", new Action<LocalPluginContext>(ExecutePostDisassociates)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostDisassociates(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            // TODO: Implement your custom Plug-in business logic.
            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService tracingService = localContext.TracingService;

            try
            {

                // The InputParameters collection contains all the data passed in the message request.
                if (!context.InputParameters.Contains("Target")) { return; }

                //Ensure that the plugin code executes only when the rquest is coming from "Opportunity"
                EntityReference ef = (EntityReference)context.InputParameters["Target"];
                if (ef.LogicalName == "opportunity")
                {
                    //Ensure that the plugin code executes only when adding competitor to and opportunity
                    Relationship relationship = (Relationship)context.InputParameters["Relationship"];
                    if (relationship.SchemaName == "opportunitycompetitors_association")
                    {

                        // Get Related Entities 
                        EntityReferenceCollection re = (EntityReferenceCollection)context.InputParameters["RelatedEntities"];
                        
                        Guid oppId = (Guid)ef.Id;

                        XrmServiceContext crm = new XrmServiceContext(localContext.OrganizationService);
                       
                        IEnumerable<Entity> competitors = from c in crm.OpportunityCompetitorsSet
                                                      where c.OpportunityId == oppId
                                                      select c;

                        var count = competitors.Count();

                        if (count <= 0)
                        {
                            Entity opp = new Entity("opportunity");
                            opp["opportunityid"] = ((EntityReference)ef).Id;
                            opp["vth_competitor"] = false;
                            service.Update(opp);
                        }
                        
                    }
                }
            }
            catch (FaultException ex)
            {
                GBSPluginExceptionLog.LogException(localContext.OrganizationService, localContext.PluginExecutionContext, localContext.TracingService, GetType().Module.ScopeName, ex);
            }
        }
    }
}
