USE [CRM_Staging]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
If  Object_ID('[dbo].[Company]') IS NOT NULL

DROP TABLE [dbo].[Company]

GO

BEGIN
CREATE TABLE [dbo].[Company]
(
	[AccountId] [uniqueidentifier] NULL DEFAULT(NEWID()),
	[AccountCategoryCode] [int] NULL,
	Address1_AddressTypeCode [int] NULL,
	[Address1_County] [nvarchar] (50) null,
    [Address1_Fax] [nvarchar] (20) null,
    [Address1_Latitude] [float] (53) null,
    [Address1_Longitude] [float] (53) null,
    [Address1_PostOfficeBox] [nvarchar] (20)null ,
    [Address1_PrimaryContactName] [nvarchar] (150) null,
    [Address1_Telephone2] [nvarchar] (50) null,
    [Address1_Telephone3] [nvarchar] (50) null,
    [Address1_UPSZone] [nvarchar] (4) null,
    [Address1_UTCOffset] [int] null,
    [Address1_AddressId] [uniqueidentifier] null,
    [Address1_City] [nvarchar] (200) null,
    [Address1_Country] [nvarchar] (200) null,
    [Address1_FreightTermsCode] [nvarchar] (200) null,
    [Address1_Line1] [nvarchar] (200) null,
    [Address1_Line2] [nvarchar] (200) null,
    [Address1_Line3] [nvarchar] (200) null,
    [Address1_Name] [nvarchar] (200) null,
    [Address1_PostalCode] [nvarchar] (20) null,
    [Address1_ShippingMethodCode] [nvarchar] (20) null,
    [Address1_StateOrProvince] [nvarchar] (200) null,
    [Address1_Telephone1] [nvarchar] (200) null,
	[TerritoryId] [uniqueidentifier] NULL,
	[DefaultPriceLevelId] [uniqueidentifier] NULL,
	[CustomerSizeCode] [int] NULL,
	[PreferredContactMethodCode] [int] NULL,
	[CustomerTypeCode] [int] NULL,
	[AccountRatingCode] [int] NULL,
	[IndustryCode] [int] NULL,
	[TerritoryCode] [int] NULL,
	[AccountClassificationCode] [int] NULL,
	[BusinessTypeCode] [int] NULL,
	[OwningBusinessUnit] [uniqueidentifier] NULL,
	[OwnerId] [uniqueidentifier] NULL,
	[OwnerIdType] [int] NULL,
	[OriginatingLeadId] [uniqueidentifier] NULL,
	[PaymentTermsCode] [int] NULL,
	[ShippingMethodCode] [int] NULL,
	[PrimaryContactId] [uniqueidentifier] NULL,
	[onyx_PrimaryContactId] [int] NULL,
	[ParticipatesInWorkflow] [bit] NULL,
	[Name] [nvarchar](160) NULL,
	[AccountNumber] [nvarchar](20) NULL,
	[Revenue] [money] NULL,
	[OwningTeam] [uniqueidentifier] null,
    [OwningUser] [uniqueidentifier] null,
	[Revenue_Base] [money] NULL,
	[NumberOfEmployees] [int] NULL,
	[Description] [nvarchar](max) NULL,
	[SIC] [nvarchar](20) NULL,
	[OwnershipCode] [int] NULL,
	[MarketCap] [money] NULL,
	[MarketCap_Base] [money] NULL,
	[SharesOutstanding] [int] NULL,
	[TickerSymbol] [nvarchar](10) NULL,
	[StockExchange] [nvarchar](20) NULL,
	[WebSiteURL] [nvarchar](200) NULL,
	[FtpSiteURL] [nvarchar](200) NULL,
	[EMailAddress1] [nvarchar](100) NULL,
	[EMailAddress2] [nvarchar](100) NULL,
	[EMailAddress3] [nvarchar](100) NULL,
	[DoNotPhone] [bit] NULL,
	[DoNotFax] [bit] NULL,
	[Telephone1] [nvarchar](50) NULL,
	[DoNotEMail] [bit] NULL,
	[Telephone2] [nvarchar](50) NULL,
	[Fax] [nvarchar](50) NULL,
	[Telephone3] [nvarchar](50) NULL,
	[DoNotPostalMail] [bit] NULL,
	[DoNotBulkEMail] [bit] NULL,
	[DoNotBulkPostalMail] [bit] NULL,
	[CreditLimit] [money] NULL,
	[CreditLimit_Base] [money] NULL,
	[CreditOnHold] [bit] NULL,
	[IsPrivate] [bit] NULL,
	[CreatedOn] [datetime] NULL,
	[CreatedBy] [uniqueidentifier] NULL,
	[ModifiedOn] [datetime] NULL,
	[ModifiedBy] [uniqueidentifier] NULL,
	[ParentAccountId] [uniqueidentifier] NULL,
	[onyx_ParentCompanyId] [int] NULL,
	[Aging30] [money] NULL,
	[Aging30_Base] [money] NULL,
	[StateCode] [int]  NULL,
	[Aging60] [money] NULL,
	[Aging60_Base] [money] NULL,
	[StatusCode] [int] NULL,
	[Aging90] [money] NULL,
	[Aging90_Base] [money] NULL,
	[PreferredAppointmentDayCode] [int] NULL,
	[PreferredSystemUserId] [uniqueidentifier] NULL,
	[PreferredAppointmentTimeCode] [int] NULL,
	[Merged] [bit] NULL,
	[DoNotSendMM] [bit] NULL,
	[MasterId] [uniqueidentifier] NULL,
	[LastUsedInCampaign] [datetime] NULL,
	[PreferredServiceId] [uniqueidentifier] NULL,
	[PreferredEquipmentId] [uniqueidentifier] NULL,
	[ExchangeRate] [decimal](23, 10) NULL,
	[UTCConversionTimeZoneCode] [int] NULL,
	[OverriddenCreatedOn] [datetime] NULL,
	[TimeZoneRuleVersionNumber] [int] NULL,
	[ImportSequenceNumber] [int] NULL,
	[TransactionCurrencyId] [uniqueidentifier] NULL,
	[YomiName] [nvarchar](160) NULL,
	[vth_BedCount] [nvarchar](200) null,
    [vth_BudgetRequest] [nvarchar] (200) null,
    [vth_Country] [nvarchar] (200) null,
    [vth_Duns] [nvarchar] (200) null,
    [vth_ExportStatus] [nvarchar] (200)  null,
    [vth_FiscalYear] [nvarchar] (200) null,
    [vth_GPOId] [uniqueidentifier]  null,
    [vth_LastExportReview] [datetime] null,
    [vth_MarketSectorId] [uniqueidentifier] null,
    [vth_PrimaryPhone] [nvarchar] (200) null,
    [vth_Source] [nvarchar] (200) null,
    [vth_Subtype] [nvarchar] (200) null,
    [vth_TaxExempt] [bit] null,
    [vth_TaxId] [nvarchar] (200) null,
   
    [vth_Tier1GoldStar] [bit] null,
    [vth_UseAsReference] [bit] null,
    [vth_Valid] [bit] null,
    [vth_CreditStatus] [nvarchar] (200) null, 
    [vth_Expiration] [datetime] null,
    [vth_EIN] [nvarchar] (200) null,
    [vth_PreferredCarrier] [nvarchar] (200) null,
    [vth_CarrierAccountNumber] [nvarchar] (200) null, 
    [vth_ServicePartner] [bit] null, 
	[vth_state] [int],
	[vth_buildingtype] [int],
	[vth_facilitytype][int],
	[vth_pricing][int],
	[RowAction] [nvarchar] (25) NULL
)
END