USE [CRM_Staging]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
If  Object_ID('[dbo].[Quote]') IS NOT NULL

DROP TABLE [dbo].[Quote]
GO
BEGIN
CREATE TABLE [dbo].[Quote](
	[QuoteId] [uniqueidentifier] null DEFAULT(NEWID()),
	[OwningBusinessUnit] [uniqueidentifier] NULL,
	[PriceLevelId] [uniqueidentifier] null,
	[OpportunityId] [uniqueidentifier] NULL,
	
[QuoteNumber] [nvarchar](200),
[RevisionNumber] [int],
[Name] [nvarchar](600) null,
[PricingErrorCode] [int],
[Description] [nvarchar](200),
[DiscountAmount] [money],
[FreightAmount] [money],
[TotalAmount] [money],
[TotalLineItemAmount] [money],
[TotalLineItemDiscountAmount] [money],
[TotalAmountLessFreight] [money],
[EffectiveFrom] [datetime],
[TotalTax] [money],
[TotalDiscountAmount] [money],
[EffectiveTo] [datetime],
[ExpiresOn] [datetime],
[ClosedOn] [datetime],
[RequestDeliveryBy] [datetime],
[ShippingMethodCode] [int],
[PaymentTermsCode] [int],
[FreightTermsCode] [int],
[CreatedBy] [uniqueidentifier],
[CreatedOn] [datetime],
[ModifiedBy] [uniqueidentifier],
[ModifiedOn] [datetime],
[StateCode] [int],
[StatusCode] [int],
[ShipTo_Name] [nvarchar](400),
[VersionNumber] [timestamp],
[ShipTo_Line1] [nvarchar](800),
[ShipTo_Line2] [nvarchar](800),
[ShipTo_Line3] [nvarchar](800),
[ShipTo_City] [nvarchar](160),
[ShipTo_StateOrProvince] [nvarchar](100),
[ShipTo_Country] [nvarchar](160),
[ShipTo_PostalCode] [nvarchar](40),
[WillCall] [bit],
[ShipTo_Telephone] [nvarchar](100),
[BillTo_Name] [nvarchar](400),
[ShipTo_FreightTermsCode] [int],
[ShipTo_Fax] [nvarchar](100),
[BillTo_Line1] [nvarchar](800),
[BillTo_Line2] [nvarchar](800),
[BillTo_Line3] [nvarchar](800),
[BillTo_City] [nvarchar](160),
[BillTo_StateOrProvince] [nvarchar](100),
[BillTo_Country] [nvarchar](160),
[BillTo_PostalCode] [nvarchar](40),
[BillTo_Telephone] [nvarchar](100),
[BillTo_Fax] [nvarchar](100),
[DiscountPercentage] [decimal],
[CampaignId] [uniqueidentifier],
[ShipTo_AddressId] [uniqueidentifier],
[ShipTo_ContactName] [nvarchar](300),
[BillTo_AddressId] [uniqueidentifier],
[BillTo_ContactName] [nvarchar](300),
[TimeZoneRuleVersionNumber] [int],
[UniqueDscId] [uniqueidentifier],
[ImportSequenceNumber] [int],
[ExchangeRate] [decimal],
[OverriddenCreatedOn] [datetime],
[UTCConversionTimeZoneCode] [int],
[TransactionCurrencyId] [uniqueidentifier],
[TotalLineItemDiscountAmount_Base] [money],
[TotalAmountLessFreight_Base] [money],
[DiscountAmount_Base] [money],
[FreightAmount_Base] [money],
[TotalAmount_Base] [money],
[TotalDiscountAmount_Base] [money],
[TotalTax_Base] [money],
[TotalLineItemAmount_Base] [money],
[CreatedOnBehalfBy] [uniqueidentifier],
[OwnerId] [uniqueidentifier],
[ModifiedOnBehalfBy] [uniqueidentifier],
[CustomerId] [uniqueidentifier],
[OwnerIdType] [int],
[CustomerIdName] [nvarchar](800),
[CustomerIdType] [int],
[CustomerIdYomiName] [nvarchar](800),

[vth_PrimaryContactId] [uniqueidentifier] null,
[vth_BillToCompanyId] [uniqueidentifier],
[vth_ShipToCompanyId] [uniqueidentifier],
[vth_billtocontactid] [uniqueidentifier],
[vth_shiptocontactid] [uniqueidentifier],
[vth_VerathonRefId][int]
)
END