USE [CRM_Staging]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
If  Object_ID('[dbo].[Order]') IS NOT NULL

DROP TABLE [dbo].[Order]
GO
BEGIN
CREATE TABLE [dbo].[Order](

[SalesOrderId] [uniqueidentifier],
[OpportunityId] [uniqueidentifier],
[QuoteId] [uniqueidentifier],
[PriorityCode] [int],
[SubmitStatus] [int],
[SubmitDate] [datetime],
[OwningBusinessUnit] [uniqueidentifier],
[SubmitStatusDescription] [nvarchar](200),
[PriceLevelId] [uniqueidentifier],
[LastBackofficeSubmit] [datetime],
[OrderNumber] [nvarchar](200),
[Name] [nvarchar](600),
[PricingErrorCode] [int],
[Description] [nvarchar](200),
[DiscountAmount] [money],
[FreightAmount] [money],
[TotalAmount] [money],
[TotalLineItemAmount] [money],
[TotalLineItemDiscountAmount] [money],
[TotalAmountLessFreight] [money],
[TotalDiscountAmount] [money],
[RequestDeliveryBy] [datetime],
[TotalTax] [money],
[ShippingMethodCode] [int],
[PaymentTermsCode] [int],
[FreightTermsCode] [int],
[CreatedBy] [uniqueidentifier],
[CreatedOn] [datetime],
[ModifiedBy] [uniqueidentifier],
[ModifiedOn] [datetime],
[StateCode] [int],
[StatusCode] [int],
[ShipTo_Name] [nvarchar](400),
[VersionNumber] [timestamp],
[ShipTo_Line1] [nvarchar](800),
[ShipTo_Line2] [nvarchar](800),
[ShipTo_Line3] [nvarchar](800),
[ShipTo_City] [nvarchar](160),
[ShipTo_StateOrProvince] [nvarchar](100),
[ShipTo_Country] [nvarchar](160),
[ShipTo_PostalCode] [nvarchar](40),
[WillCall] [bit],
[ShipTo_Telephone] [nvarchar](100),
[BillTo_Name] [nvarchar](400),
[ShipTo_FreightTermsCode] [int],
[ShipTo_Fax] [nvarchar](100),
[BillTo_Line1] [nvarchar](800),
[BillTo_Line2] [nvarchar](800),
[BillTo_Line3] [nvarchar](800),
[BillTo_City] [nvarchar](160),
[BillTo_StateOrProvince] [nvarchar](100),
[BillTo_Country] [nvarchar](160),
[BillTo_PostalCode] [nvarchar](40),
[BillTo_Telephone] [nvarchar](100),
[BillTo_Fax] [nvarchar](100),
[DiscountPercentage] [decimal],
[BillTo_ContactName] [nvarchar](1000),
[CampaignId] [uniqueidentifier],
[BillTo_AddressId] [uniqueidentifier],
[ShipTo_AddressId] [uniqueidentifier],
[IsPriceLocked] [bit],
[DateFulfilled] [datetime],
[ShipTo_ContactName] [nvarchar](1000),
[UTCConversionTimeZoneCode] [int],
[TransactionCurrencyId] [uniqueidentifier],
[TimeZoneRuleVersionNumber] [int],
[ImportSequenceNumber] [int],
[ExchangeRate] [decimal],
[OverriddenCreatedOn] [datetime],
[TotalLineItemAmount_Base] [money],
[TotalDiscountAmount_Base] [money],
[TotalAmountLessFreight_Base] [money],
[TotalAmount_Base] [money],
[DiscountAmount_Base] [money],
[FreightAmount_Base] [money],
[TotalLineItemDiscountAmount_Base] [money],
[TotalTax_Base] [money],
[CustomerId] [uniqueidentifier],
[CreatedOnBehalfBy] [uniqueidentifier],
[OwnerId] [uniqueidentifier],
[ModifiedOnBehalfBy] [uniqueidentifier],
[OwnerIdType] [int],
[CustomerIdType] [int],
[CustomerIdName] [nvarchar](800),
[CustomerIdYomiName] [nvarchar](800),
[vth_PrimaryContactId] [uniqueidentifier],
[vth_SoldToCreditStatus] [int],
[vth_SoldToTaxExempt] [bit],
[vth_SoldToExpiration] [datetime],
[vth_SoldToTaxExemptNumber] [nvarchar](200),
[vth_SoldToCreditLimit] [int],
[vth_BillToContactId] [uniqueidentifier],
[vth_ShipToContactId] [uniqueidentifier],
[vth_BillToTaxExempt] [bit],
[vth_BillToExpiration] [datetime],
[vth_BillToTaxExemptNumber] [nvarchar](200),
[vth_BillToCreditStatus] [int],
[vth_BillToCreditLimit] [int],
[vth_TerritoryId] [uniqueidentifier],
[vth_SalesService] [bit],
[vth_Destination] [int],
[vth_OrderType] [int],
[vth_PONumber] [nvarchar](200),
[vth_Attention] [nvarchar](200),
[vth_Carrier] [int],
[vth_CaseId] [uniqueidentifier],
[vth_ShipToCompanyId] [uniqueidentifier],
[vth_BillToCompanyId] [uniqueidentifier],
[vth_BillToContactDetails] [nvarchar](200),
[vth_ShipToContactDetails] [nvarchar](200),
[vth_OriginalOrderId] [uniqueidentifier],
[vth_OrderNumber] [int],
[vth_CreditCardPreAuthTransactionId] [nvarchar](200),
[vth_salesrepid] [GUID]



)END